In [1]:
import numpy as np

In [2]:
np


<module 'numpy' from '/home/george/assets/venvs/venv-jupyter/lib/python3.11/site-packages/numpy/__init__.py'>

In [4]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [5]:
x= np.linspace(0,5,10)
y = np.linspace(0,5,10)

In [6]:
x

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [7]:
np.meshgrid(x,y)

(array([[0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
         2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ],
        [0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
         2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ],
        [0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
         2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ],
        [0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
         2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ],
        [0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
         2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ],
        [0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
         2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ],
        [0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
         2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ],
        [0.        , 0.5555